config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'bye', to: 'pages#bye'
  get 'directions', to: 'pages#directions'
  get 'home', to: 'pages#home'

  resources :participants
  resource :reading, only: [:show, :create]
  resources :activities

  get 'dashboard', to: 'dashboard#show'
  get 'dashboard/participants', defaults: { format: :csv }
  get 'dashboard/readings', defaults: { format: :csv }
  get 'dashboard/activities', defaults: { format: :csv }
end

app/models/participant.rb
class Participant < ApplicationRecord
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email
  validates_presence_of :passcode
  validates_presence_of :class_code
  validates_presence_of :section

  has_many :readings, class_name: "Reading", foreign_key: "participant_id", dependent: :destroy

  def self.class_codes
    [
      "EDPSY 14",
      "EDPSY 10",
      "EDPSY 11",
      "EDPSY 101",
      "N/A"
    ]
  end

  def self.section_names
    [
      "001",
      "002",
      "N/A"
    ]
  end

  def random_reading_order(num_readings, randomized)
    if randomized
      array = (1..num_readings).to_a
      array.shuffle(random: Random.new(self.id))
    else
      (1..num_readings).to_a
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, except: [:new, :create]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
    session[:participant_id] = nil
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        session[:participant_id] = @participant.id

        format.html { redirect_to directions_path }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit(:first_name, :last_name, :email, :class_code, :section, :passcode)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <div class="field">
    <%= form.label :first_name, class: 'label' %>
    <div class="control">
      <%= form.text_field :first_name, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :last_name, class: 'label' %>
    <div class="control">
      <%= form.text_field :last_name, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :email, class: 'label' %>
    <div class="control">
      <%= form.text_field :email, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :class_code, class: 'label' %>
    <div class="control">
      <%= form.text_field :class_code, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :section, class: 'label' %>
    <div class="control">
      <%= form.text_field :section, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :passcode, class: 'label' %>
    <div class="control">
      <%= form.text_field :passcode, class: 'input' %>
    </div>
  </div>

  <div class="field buttons">
    <%= form.submit class: 'button is-link' %>
    <% if participant.persisted? %>
      <%= link_to 'Delete', participant, method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
      <%= link_to "Cancel", participant, class: "button" %>
    <% else %>
      <%= link_to "Cancel", participants_path, class: "button" %>
    <% end %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1 class="title">Edit Participant</h1>

<%= render 'form', participant: @participant %>

app/views/participants/index.html.erb
<h1 class="title">Participants</h1>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Class code</th>
        <th>Section</th>
        <th>Passcode</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @participants.each do |participant| -%>
        <tr>
          <td><%= participant.first_name %></td>
          <td><%= participant.last_name %></td>
          <td><%= participant.email %></td>
          <td><%= participant.class_code %></td>
          <td><%= participant.section %></td>
          <td><%= participant.passcode %></td>
          <td>
            <div class="buttons">
              <%= link_to 'View', participant, class: "button is-small" %>
              <%= link_to 'Edit', edit_participant_path(participant), class: "button is-small" %>
              <%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' },
                class: "button is-small is-danger" %>
            </div>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/participants/new.html.erb
<div class="columns is-centered">
  <div class="column is-half">

    <h1 class="title">Participant Sign In</h1>

    <%= form_with(model: @participant, local: true) do |form| %>
      <%= render "shared/error_messages", object: form.object %>

      <div class="columns">
        <div class="column">
          <div class="field">
            <%= form.label :first_name, class: 'label' %>
            <div class="control">
              <%= form.text_field :first_name, class: 'input' %>
            </div>
          </div>
        </div>

        <div class="column">
          <div class="field">
            <%= form.label :last_name, class: 'label' %>
            <div class="control">
              <%= form.text_field :last_name, class: 'input' %>
            </div>
          </div>
        </div>
      </div>

      <div class="columns">
        <div class="column">
          <div class="field">
            <%= form.label :email, class: 'label' %>
            <div class="control">
              <%= form.text_field :email, class: 'input' %>
            </div>
          </div>
        </div>

        <div class="column">
          <div class="field">
            <%= form.label :passcode, "Retype Passcode", class: 'label' %>
            <div class="control">
              <%= form.text_field :passcode, class: 'input',
              placeholder: 'e.g., Last four digits of cellphone'%>
            </div>
          </div>
        </div>
      </div>

      <div class="columns">
        <div class="column">
          <div class="field">
            <%= form.label :class_code, class: 'label' %>
            <div class="control">
              <div class="select is-fullwidth">
                <%= form.select :class_code, Participant.class_codes.map { |v| [v,v] },
                  class: "is-fullwidth", include_blank: true %>
              </div>
            </div>
          </div>
        </div>

        <div class="column">
          <div class="field">
            <%= form.label :section, class: 'label' %>
            <div class="control">
              <div class="select is-fullwidth">
                <%= form.select :section, Participant.section_names.map { |v| [v,v] },
                  class: "is-fullwidth", include_blank: true %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="field buttons">
        <%= form.submit class: 'button is-link' %>
      </div>
    <% end %>

  </div>
</div>

app/views/participants/show.html.erb
<h1 class="title">Participant</h1>

<p>
  <strong>First name:</strong>
  <%= @participant.first_name %>
</p>
<p>
  <strong>Last name:</strong>
  <%= @participant.last_name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>
<p>
  <strong>Class code:</strong>
  <%= @participant.class_code %>
</p>
<p>
  <strong>Section:</strong>
  <%= @participant.section %>
</p>
<p>
  <strong>Passcode:</strong>
  <%= @participant.passcode %>
</p>

<br>
<div class="buttons">
  <%= link_to 'Back', participants_path, class: "button" %>
  <%= link_to 'Edit', edit_participant_path(@participant), class: "button" %>
  <%= link_to 'Destroy', @participant, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger" %>
</div>