config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'bye', to: 'pages#bye'
  get 'directions', to: 'pages#directions'
  get 'home', to: 'pages#home'

  resources :participants
  resource :reading, only: [:show, :create]
  resources :activities

  get 'dashboard', to: 'dashboard#show'
  get 'dashboard/participants', defaults: { format: :csv }
  get 'dashboard/readings', defaults: { format: :csv }
  get 'dashboard/activities', defaults: { format: :csv }
end

app/views/pages/about.html.erb
<h1 class="title">About us</h1>

app/views/pages/bye.html.erb
<section class="hero is-fullheight is-info is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-size-1">
        Thank you
      </h1>
      <%= link_to "Next Participant", home_path, class: "button is-info is-inverted is-medium" %>
    </div>
  </div>
</section>

app/views/pages/directions.html.erb
<tutorial-container></tutorial-container>

app/views/pages/home.html.erb
<section class="hero is-fullheight is-info is-bold">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-size-1">
        Welcome!
      </h1>
      <h2 class="subtitle is-size-4">
        This is the second part of the study.
      </h2>

      <div class="pt-4">
        <%= link_to new_participant_path, class: "button is-info is-inverted is-large" do %>
          Get Started &rarr;
        <% end %>
      </div>
    </div>
  </div>
</section>