config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'bye', to: 'pages#bye'
  get 'directions', to: 'pages#directions'
  get 'home', to: 'pages#home'

  resources :participants
  resource :reading, only: [:show, :create]
  resources :activities

  get 'dashboard', to: 'dashboard#show'
  get 'dashboard/participants', defaults: { format: :csv }
  get 'dashboard/readings', defaults: { format: :csv }
  get 'dashboard/activities', defaults: { format: :csv }
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :participant
  validates_presence_of :text_id
  validates_presence_of :order
  validates_presence_of :action_string
  validates_presence_of :action_type
  validates_presence_of :time_since_page_load
  validates_presence_of :time_since_tooltip_open
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_admin, except: [:create]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.page(params[:page])
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.participant_id = session[:participant_id]

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:participant_id, :text_id, :order, :action_string, :action_type, :time_since_page_load, :time_since_tooltip_open, :comment)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <div class="field">
    <%= form.label :participant_id, class: 'label' %>
    <div class="control">
      <%= form.number_field :participant_id, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :text_id, class: 'label' %>
    <div class="control">
      <%= form.number_field :text_id, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :order, class: 'label' %>
    <div class="control">
      <%= form.number_field :order, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :action_string, class: 'label' %>
    <div class="control">
      <%= form.text_field :action_string, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :action_type, class: 'label' %>
    <div class="control">
      <%= form.text_field :action_type, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :time_since_page_load, class: 'label' %>
    <div class="control">
      <%= form.number_field :time_since_page_load, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :time_since_tooltip_open, class: 'label' %>
    <div class="control">
      <%= form.number_field :time_since_tooltip_open, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :comment, class: 'label' %>
    <div class="control">
      <%= form.text_field :comment, class: 'input' %>
    </div>
  </div>

  <div class="field buttons">
    <%= form.submit class: 'button is-link' %>
    <% if activity.persisted? %>
      <%= link_to 'Delete', activity, method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
      <%= link_to "Cancel", activity, class: "button" %>
    <% else %>
      <%= link_to "Cancel", activities_path, class: "button" %>
    <% end %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1 class="title">Edit Activity</h1>

<%= render 'form', activity: @activity %>

app/views/activities/index.html.erb
<h1 class="title">Activities</h1>

<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Participant</th>
        <th>Text</th>
        <th>Order</th>
        <th>Action string</th>
        <th>Action type</th>
        <th>Time since page load</th>
        <th>Time since tooltip open</th>
        <th>Comment</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @activities.each do |activity| -%>
        <tr>
          <td><%= activity.participant_id %></td>
          <td><%= activity.text_id %></td>
          <td><%= activity.order %></td>
          <td><%= activity.action_string %></td>
          <td><%= activity.action_type %></td>
          <td><%= activity.time_since_page_load %></td>
          <td><%= activity.time_since_tooltip_open %></td>
          <td><%= activity.comment %></td>
          <td>
            <div class="buttons">
              <%= link_to 'View', activity, class: "button is-small" %>
              <%= link_to 'Edit', edit_activity_path(activity), class: "button is-small" %>
              <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' },
                class: "button is-small is-danger" %>
            </div>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
</div>

app/views/activities/new.html.erb
<h1 class="title">New Activity</h1>

<%= render 'form', activity: @activity %>

app/views/activities/show.html.erb
<h1 class="title">Activity</h1>

<p>
  <strong>Participant:</strong>
  <%= @activity.participant_id %>
</p>
<p>
  <strong>Text:</strong>
  <%= @activity.text_id %>
</p>
<p>
  <strong>Order:</strong>
  <%= @activity.order %>
</p>
<p>
  <strong>Action string:</strong>
  <%= @activity.action_string %>
</p>
<p>
  <strong>Action type:</strong>
  <%= @activity.action_type %>
</p>
<p>
  <strong>Time since page load:</strong>
  <%= @activity.time_since_page_load %>
</p>
<p>
  <strong>Time since tooltip open:</strong>
  <%= @activity.time_since_tooltip_open %>
</p>
<p>
  <strong>Comment:</strong>
  <%= @activity.comment %>
</p>

<br>
<div class="buttons">
  <%= link_to 'Back', activities_path, class: "button" %>
  <%= link_to 'Edit', edit_activity_path(@activity), class: "button" %>
  <%= link_to 'Destroy', @activity, method: :delete, data: { confirm: 'Are you sure?' }, class: "button is-danger" %>
</div>